name: "Minio Action Cache Downloader"
author: Infovista
description: "S3 actions cache with actions/cache@v2 passthrough"
inputs:
  endpoint:
    description: "s3 / minio endpoint, see: https://docs.min.io/docs/javascript-client-api-reference.html"
    required: false
    default: s3.amazonaws.com
  port:
    description: minio port
    required: false
  insecure:
    description: use insecure http connection to minio
    required: false
  accessKey:
    description: s3 / minio accessKey
    required: true
  secretKey:
    description: s3 / minio secretKey
    required: true
  bucket:
    description: s3 / minio bucket
    required: true
  path:
    description: "A list of files, directories, and wildcard patterns to cache and restore"
    required: true
  key:
    description: "An explicit key for restoring the cache"
    required: true

outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"

runs:
  using: node16
  main: "dist/restore/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
